### ISSUE TITLE
Failure To Build In Arch

### ISSUE THREAD

**Issue by wesleyotugo** [rilian-la-te/xfce4-sntray-plugin#10]
`gobject-2.0.vapi:157.37-157.57: error: The type name `GLib.DuplicateFunc' could not be found
                public T dup_data<T> (string key, GLib.DuplicateFunc<T> dup_func);
                                                  ^^^^^^^^^^^^^^^^^^^^^
gobject-2.0.vapi:160.44-160.64: error: The type name `GLib.DuplicateFunc' could not be found
                public T dup_qdata<T> (GLib.Quark quark, GLib.DuplicateFunc<T> dup_func);
                                                         ^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 2 error(s), 48 warning(s)
make[2]: *** [lib/CMakeFiles/internal.dir/build.make:95: lib/internal_valac.stamp] Error 1
make[1]: *** [CMakeFiles/Makefile2:206: lib/CMakeFiles/internal.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
`

Affects all of vala-panel plugins except appmenu

**Comment by rilian-la-te** [comment]
remove vapi/glib-2.0.vala in PKGBUILD
