### ISSUE TITLE
[Manjaro/Arch] Applet does not build with vala plugin enabled

### ISSUE THREAD

**Issue by IKRadulov** [rilian-la-te/xfce4-sntray-plugin#12]
The applet does not build with vala plugin enabled couse it can't find 
vala-panel-compat.h but vala-panel.vapi has vala-panel-compat.h

fatal error: vala-panel-compat.h: No such file or directory
 #include <vala-panel-compat.h>
                               ^
compilation terminated.
make[2]: *** [src/CMakeFiles/sntray-valapanel.dir/build.make:283: src/CMakeFiles/sntray-valapanel.dir/vala-panel-sntray-applet.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:228: src/CMakeFiles/sntray-valapanel.dir/all] Error 2
make: *** [Makefile:150: all] Error 2

**Comment by rilian-la-te** [comment]
Will fix it. But this is vala-panel bug, not this.
