### ISSUE TITLE
build fail?

### ISSUE THREAD

**Issue by SolarAquarion** [rilian-la-te/xfce4-sntray-plugin#14]
/tmp/trizen-solaraquarion/xfce4-sntray-plugin/src/xfce4-sntray-plugin-0.4.4/src/snitemproxy.c: In function ‘status_notifier_status_to_string’:
/tmp/trizen-solaraquarion/xfce4-sntray-plugin/src/xfce4-sntray-plugin-0.4.4/src/snitemproxy.c:419:9: warning: ‘str’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  return str;
         ^~~
[ 43%] Building C object src/CMakeFiles/sntray-xfce.dir/qrichtextparser.c.o
[ 44%] Building C object src/CMakeFiles/sntray-xfce.dir/config.c.o
[ 46%] Building C object src/CMakeFiles/sntray-xfce.dir/xfce4-sntray-applet.c.o
[ 47%] Building C object src/CMakeFiles/sntray-xfce.dir/sntray.gresource.c.o
[ 49%] Linking C shared library libsntray-xfce.so
[ 53%] Built target sntray-xfce
[ 55%] Generating vala-panel-sntray-applet.c
vala-panel.vapi:185.2-185.29: error: `Config' already contains a definition for `DATADIR'
	public const string DATADIR;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel-sntray.vapi:137.2-137.29: note: previous definition of `DATADIR' was here
	public const string DATADIR;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel.vapi:187.2-187.37: error: `Config' already contains a definition for `GETTEXT_PACKAGE'
	public const string GETTEXT_PACKAGE;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel-sntray.vapi:139.2-139.37: note: previous definition of `GETTEXT_PACKAGE' was here
	public const string GETTEXT_PACKAGE;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel.vapi:189.2-189.36: error: `Config' already contains a definition for `INSTALL_PREFIX'
	public const string INSTALL_PREFIX;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel-sntray.vapi:141.2-141.36: note: previous definition of `INSTALL_PREFIX' was here
	public const string INSTALL_PREFIX;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel.vapi:191.2-191.32: error: `Config' already contains a definition for `LOCALE_DIR'
	public const string LOCALE_DIR;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel-sntray.vapi:143.2-143.32: note: previous definition of `LOCALE_DIR' was here
	public const string LOCALE_DIR;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel.vapi:193.2-193.32: error: `Config' already contains a definition for `PKGDATADIR'
	public const string PKGDATADIR;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel-sntray.vapi:145.2-145.32: note: previous definition of `PKGDATADIR' was here
	public const string PKGDATADIR;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel.vapi:195.2-195.34: error: `Config' already contains a definition for `PLUGINS_DATA'
	public const string PLUGINS_DATA;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel-sntray.vapi:147.2-147.34: note: previous definition of `PLUGINS_DATA' was here
	public const string PLUGINS_DATA;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel.vapi:197.2-197.39: error: `Config' already contains a definition for `PLUGINS_DIRECTORY'
	public const string PLUGINS_DIRECTORY;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel-sntray.vapi:149.2-149.39: note: previous definition of `PLUGINS_DIRECTORY' was here
	public const string PLUGINS_DIRECTORY;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel.vapi:199.2-199.34: error: `Config' already contains a definition for `RELEASE_NAME'
	public const string RELEASE_NAME;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel-sntray.vapi:151.2-151.34: note: previous definition of `RELEASE_NAME' was here
	public const string RELEASE_NAME;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel.vapi:201.2-201.29: error: `Config' already contains a definition for `VERSION'
	public const string VERSION;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel-sntray.vapi:153.2-153.29: note: previous definition of `VERSION' was here
	public const string VERSION;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel.vapi:203.2-203.34: error: `Config' already contains a definition for `VERSION_INFO'
	public const string VERSION_INFO;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel-sntray.vapi:155.2-155.34: note: previous definition of `VERSION_INFO' was here
	public const string VERSION_INFO;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 10 error(s), 0 warning(s)
make[2]: *** [src/CMakeFiles/sntray-valapanel.dir/build.make:113: src/sntray-valapanel_valac.stamp] Error 1
make[1]: *** [CMakeFiles/Makefile2:540: src/CMakeFiles/sntray-valapanel.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by rilian-la-te** [comment]
I am looking for it now.

What vala-panel version are you have?

**Comment by SolarAquarion** [comment]
41%] Linking C executable vala-panel-runner
[ 41%] Built target vala-panel-runner
[ 42%] Generating kbled.c
vala-panel.vapi:11.2-11.44: error: `ValaPanel' already contains a definition for `Applet'
	public abstract class Applet : Gtk.EventBox {
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cvalapanel.vapi:46.2-46.39: note: previous definition of `Applet' was here
	public abstract class Applet : Gtk.Bin {
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel.vapi:185.2-185.29: error: `Config' already contains a definition for `DATADIR'
	public const string DATADIR;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cvalapanel.vapi:284.4-284.31: note: previous definition of `DATADIR' was here
   public const string DATADIR;
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel.vapi:187.2-187.37: error: `Config' already contains a definition for `GETTEXT_PACKAGE'
	public const string GETTEXT_PACKAGE;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cvalapanel.vapi:286.4-286.39: note: previous definition of `GETTEXT_PACKAGE' was here
   public const string GETTEXT_PACKAGE;
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel.vapi:189.2-189.36: error: `Config' already contains a definition for `INSTALL_PREFIX'
	public const string INSTALL_PREFIX;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cvalapanel.vapi:292.4-292.38: note: previous definition of `INSTALL_PREFIX' was here
   public const string INSTALL_PREFIX;
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel.vapi:191.2-191.32: error: `Config' already contains a definition for `LOCALE_DIR'
	public const string LOCALE_DIR;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cvalapanel.vapi:293.4-293.34: note: previous definition of `LOCALE_DIR' was here
   public const string LOCALE_DIR;
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel.vapi:193.2-193.32: error: `Config' already contains a definition for `PKGDATADIR'
	public const string PKGDATADIR;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cvalapanel.vapi:285.4-285.34: note: previous definition of `PKGDATADIR' was here
   public const string PKGDATADIR;
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel.vapi:195.2-195.34: error: `Config' already contains a definition for `PLUGINS_DATA'
	public const string PLUGINS_DATA;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cvalapanel.vapi:291.4-291.36: note: previous definition of `PLUGINS_DATA' was here
   public const string PLUGINS_DATA;
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel.vapi:197.2-197.39: error: `Config' already contains a definition for `PLUGINS_DIRECTORY'
	public const string PLUGINS_DIRECTORY;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cvalapanel.vapi:290.4-290.41: note: previous definition of `PLUGINS_DIRECTORY' was here
   public const string PLUGINS_DIRECTORY;
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel.vapi:199.2-199.34: error: `Config' already contains a definition for `RELEASE_NAME'
	public const string RELEASE_NAME;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cvalapanel.vapi:287.4-287.36: note: previous definition of `RELEASE_NAME' was here
   public const string RELEASE_NAME;
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel.vapi:201.2-201.29: error: `Config' already contains a definition for `VERSION'
	public const string VERSION;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cvalapanel.vapi:288.4-288.31: note: previous definition of `VERSION' was here
   public const string VERSION;
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vala-panel.vapi:203.2-203.34: error: `Config' already contains a definition for `VERSION_INFO'
	public const string VERSION_INFO;
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cvalapanel.vapi:289.4-289.36: note: previous definition of `VERSION_INFO' was here
   public const string VERSION_INFO;
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 11 error(s), 0 warning(s)
make[2]: *** [applets/core/kbled/CMakeFiles/kbled.dir/build.make:75: applets/core/kbled/kbled_valac.stamp] Error 1
make[1]: *** [CMakeFiles/Makefile2:706: applets/core/kbled/CMakeFiles/kbled.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

I'm getting this in vala-panel

**Comment by rilian-la-te** [comment]
vala-panel version?

**Comment by rilian-la-te** [comment]
If you are on 0.4 series (git master) - try 0.3.61, please

**Comment by rilian-la-te** [comment]
I am closing it, if it is viable for 0.3.61 - feel free to reopen.
