### ISSUE TITLE
[Bug] [Mate] Settings dialog does not have any widget in it .

### ISSUE THREAD

**Issue by IKRadulov** [rilian-la-te/xfce4-sntray-plugin#15]
So I updated to 0.4.4 on Manjaro linux . Applet build from aur . The settings dialog does not have any widgets in it , but in vala-panel applet it shows with every widget except the size scale (Do not know if it should show in vala-panel)

**Comment by rilian-la-te** [comment]
Screen, please.

**Comment by IKRadulov** [comment]
![2017-05-17 21-22-49](https://cloud.githubusercontent.com/assets/21968311/26169573/dd53d5de-3b46-11e7-8af6-397525ae2f94.png)

**Comment by rilian-la-te** [comment]
Fixed in latest master:)))
