### ISSUE TITLE
Another build issue 

### ISSUE THREAD

**Issue by IKRadulov** [rilian-la-te/xfce4-sntray-plugin#17]
[ 82%] Linking C shared library libsntray-valapanel.so
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/../../../../lib/libgtk-3.so: undefined reference to symbol 'gdk_event_get_scroll_deltas'
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/../../../../lib/libgdk-3.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/sntray-mate.dir/build.make:137: src/sntray-mate] Error 1
make[1]: *** [CMakeFiles/Makefile2:438: src/CMakeFiles/sntray-mate.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 91%] Built target sntray-valapanel
make: *** [Makefile:152: all] Error 2

**Comment by rilian-la-te** [comment]
gtk version?

**Comment by rilian-la-te** [comment]
I cannot reproduce it with latest ArchLinux gtk. Sorry.

**Comment by IKRadulov** [comment]
gtk3  3.22.15

**Comment by SolarAquarion** [comment]
I'm having the same issue

**Comment by SolarAquarion** [comment]
https://stackoverflow.com/questions/19901934/strange-linking-error-dso-missing-from-command-line update your makefile?

**Comment by SolarAquarion** [comment]
-lgtk-3 for ldflags and cflags are needed or maybe only for ldflags

**Comment by rilian-la-te** [comment]
I does not have this issue with ninja. Will look for Unix makefiles tomorrow

**Comment by rilian-la-te** [comment]
Try latest git master

**Comment by IKRadulov** [comment]
Latest git is fixed ! Compiles with no problems .
