### ISSUE TITLE
error: --header=vala-dbusmenu.h not found

### ISSUE THREAD

**Issue by nick87720z** [rilian-la-te/xfce4-sntray-plugin#18]
I get this with latest code (all it seems to be up to 7 jul).
Building with xfce support.
Full log:
```
$ LANG=C make
[  0%] Built target i18n
[  5%] Generating dbusmenu.c;dbusmenu-proxy.c;dbusmenu-gtk.c;vala-dbusmenu.vapi;vala-dbusmenu.h
error: --header=vala-dbusmenu.h not found
make[2]: *** [src/dbusmenu/CMakeFiles/vala-dbusmenu-o.dir/build.make:79: src/dbusmenu/vala-dbusmenu_valac.stamp] Error 1
make[1]: *** [CMakeFiles/Makefile2:581: src/dbusmenu/CMakeFiles/vala-dbusmenu-o.dir/all] Error 2
```
Using vala-0.34.8, gcc-6.4.0, make 4.2.1, cmake 3.7.2

**Comment by rilian-la-te** [comment]
Do you have a submodules?

**Comment by rilian-la-te** [comment]
You need to download 2 submodules - CMake and DBusMenu. And latest dbusmenu, AFAIK.

**Comment by nick87720z** [comment]
This happens with submodules. After clone i do:
git submodule init
git submodule update

**Comment by rilian-la-te** [comment]
ebuild is outdated. can you post a dbusmenu folder listing?

**Comment by nick87720z** [comment]
I can't get it working even building manually from git.
I just do:
```
$ git clone https://github.com/rilian-la-te/xfce4-sntray-plugin
$ cd xfce4-sntray-plugin
$ git submodule init
$ git submodule update
```
On last command src/dbusmenu gets this state from linked repo:
ad2d94bd9f37aa07292a0a0471b4ed3fecd52fcd

With these files:
```
CMakeLists.txt
README.md
dbusmenu-gtk.vala
dbusmenu-proxy.vala
dbusmenu.vala
gio-addons-2.0.vapi
```
Then i create build dir, enter it and run ../ccmake, enabling xfce support (btw, where is option to disable vala-panel support...).

As for ebuild, it is in my local overlay, and i was trying to update it until this fail.

**Comment by rilian-la-te** [comment]
update to latest vala-dbusmenu commit from vala-dbusmenu repo, not use linked revision,

**Comment by nick87720z** [comment]
Submodules update helped.
Why not to update submodules in this superproject?
I have seen in sume git-hosted projects, it is done regularly.
Or doing this (below) after submodule update is ok?
`$ git submodule foreach git pull origin master`

**Comment by rilian-la-te** [comment]
I often forgot to update submodules in superproject, sorry. Yes, it is ok for me. And there are a lot of generated code in submodules, so, I do not track for it in my local master (main branch of project, in fact).

**Comment by nick87720z** [comment]
I only don't how others do it - do they always manually it...
but probably, git hooks could handle this.

Btw, for ebuilds i made related proposal at BGO, they ask for use case - i have nothing of good weight to repl - obviously they will not support anything unused, and i don't know, did they discuss something similar: https://bugs.gentoo.org/640016

**Comment by rilian-la-te** [comment]
Any KDE app requires it for tray in XFCE, AFAIK) 
But if you about a git submodule approach, I do not know for now. Maybe I will update it manually.

**Comment by rilian-la-te** [comment]
Submodules updated.
