### ISSUE TITLE
Pidgin is not displayed

### ISSUE THREAD

**Issue by Malezha** [rilian-la-te/xfce4-sntray-plugin#8]
None in active window or when minimized icon is not displayed.
In applet settings pidgin isn't hidden because have not settings for it.
It's double #6?

**Comment by rilian-la-te** [comment]
Wait 17 days, please:-)

**Comment by Malezha** [comment]
I see this as birthday gift :D

**Comment by Malezha** [comment]
I waited a little more =)
Maybe if not very difficult, I can fix it, just tell me where the problem.

**Comment by rilian-la-te** [comment]
It uses libindicator? If not, it will not displayed:))) Use XEmbed for this apps:( Or KDE Translator:)

**Comment by Malezha** [comment]
I'm idiot. 
I disabled icon in pidgin.
